[package]
name = "todo"
description = "A Commandline Tasks Manager"
version = "0.1.0"
edition = "2021"
authors = ["Juan Milkah <juanmilkah@gmail.com>"]
license = "GNU GPL3"

[dependencies]
home ="0.5.11" 
